import { Dimensions, StyleSheet } from "react-native";
import { colors } from "../../themes/colors";
import { font } from "../../themes/fonts";

const heightScreen = Dimensions.get("screen").height;
const widthScreen = Dimensions.get("screen").width;

const HomeScrenStyle = StyleSheet.create({
  container: {
    width: widthScreen,
    height: heightScreen,
    backgroundColor: "#F2F3F5",
  },
  titlePrimary: {
    fontSize: font.h1.size,
    fontWeight: font.h1.weight,
    position: "absolute",
    width: 98,
    height: 29,
    left: "10%",
    top: 73,
    fontFamily: font.inter.family,
  },
  titleSecondary: {
    position: "absolute",
    width: 87,
    height: 45,
    left: "70%",
    top: 63,
    fontSize: 30,
    fontWeight: font.h1.weight,
    color: colors.gradientGreen.secondary,
    fontFamily: font.poppins.family,
  },
  inputText1: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 20,
    paddingLeft: 20,
    paddingLeft: 50,
    paddingHorizontal: 13,
    backgroundColor: "#D4DDEA",
    borderRadius: 20,
    position: "absolute",
    width: "85%",
    height: 48,
    left: "7.5%",
    top: 190,
    color: colors.textSecondary,
    fontFamily: font.inter.family,
    fontSize: font.b1.size,
    fontWeight: font.b1.weight,
  },
  inputText1Error: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 20,
    paddingLeft: 50,
    paddingHorizontal: 13,
    backgroundColor: "#D4DDEA",
    borderRadius: 20,
    position: "absolute",
    width: "85%",
    height: 48,
    left: "7.5%",
    top: 190,
    borderWidth: 1.5,
    borderColor: colors.textError,
    color: colors.textSecondary,
    fontFamily: font.inter.family,
    fontSize: font.b1.size,
    fontWeight: font.b1.weight,
  },
  errorPassword: {
    fontFamily: font.inter.family,
    fontSize: font.b2.size,
    fontWeight: font.b2.weight,
    color: colors.textError,
    position: "absolute",
    top: 240,
    left: "47%",
    maxWidth: 300,
  },
  iconEye: {
    position: "absolute",
    top: 273,
    right: "12%",
    zIndex: 2,
    color: "rgba(19, 18, 18, 0.6)",
  },
  iconKey: {
    position: "absolute",
    top: 275,
    left: "11%",
    zIndex: 2,
    color: "rgba(19, 18, 18, 0.6)",
  },

  inputText2: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-end",
    paddingVertical: 20,
    paddingLeft: 50,
    paddingHorizontal: 13,
    backgroundColor: "#D4DDEA",
    borderRadius: 20,
    position: "absolute",
    width: "85%",
    height: 48,
    left: "7.5%",
    top: 260,
    color: colors.textSecondary,
    fontFamily: font.inter.family,
    fontSize: font.b1.size,
    fontWeight: font.b1.weight,
  },
  inputText2Error: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 20,
    paddingLeft: 50,
    paddingHorizontal: 13,
    backgroundColor: "#D4DDEA",
    borderRadius: 20,
    position: "absolute",
    width: "85%",
    height: 48,
    left: "7.5%",
    top: 260,
    borderWidth: 1.5,
    borderColor: colors.textError,
    color: colors.textSecondary,
    fontFamily: font.inter.family,
    fontSize: font.b1.size,
    fontWeight: font.b1.weight,
  },

  buttonSubmit: {
    position: "absolute",
    width: "85%",
    height: 52,
    left: "7.5%",
    top: 330,
    backgroundColor: colors.gradientGreen.primary,
    borderRadius: 20,
  },
  textButtonSubmit: {
    position: "absolute",
    width: 71.69,
    height: 25.33,
    left: "41%",
    top: 12,
    fontStyle: "normal",
    fontWeight: font.b1.weight,
    fontSize: 16,
    lineHeight: 19,
    display: "flex",
    alignItems: "center",
    textAlign: "center",
    color: colors.screenBackground,
  },
  textToRestorePassword: {
    color: colors.gradientOrange.primary,
    position: "absolute",
    height: 19,
    left: "28%",
    top: 401,
    fontFamily: font.s1.family,
    fontStyle: font.s1.style,
    fontWeight: font.s1.weight,
    fontSize: font.s1.size,
  },
  line1: {
    position: "absolute",
    width: "35%",
    height: 0,
    left: "10%",
    top: 453,
    borderColor: "#A6B1C2",
    borderWidth: 1,
  },
  line2: {
    position: "absolute",
    width: "35%",
    height: 0,
    left: "55%",
    top: 453,
    borderColor: "#A6B1C2",
    borderWidth: 1,
  },
  point: {
    position: "absolute",
    width: 8,
    height: 16,
    left: "50%",
    top: 443,
    fontFamily: font.inter.family,
    fontStyle: "normal",
    fontWeight: font.b1.weight,
    fontSize: 13,
    display: "flex",
    alignItems: "center",
    textAlign: "center",
    color: "#A6B1C2",
  },
  buttonGoogle: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 64,
    paddingVertical: 16,
    position: "absolute",
    width: "85%",
    height: 52,
    left: "7.5%",
    top: 472,
    backgroundColor: colors.inputFieldBackground,
    borderRadius: 20,
  },
  iconGoogle: {
    width: 20,
    height: 20,
    position: "absolute",
    bottom: 5,
    right: "114%",
  },
  textButtonGoogle: {
    width: 138,
    height: 26,
    position: "absolute",
    top: 15,
    left: "16%",
    color: colors.textSecondary,
    fontFamily: font.poppins.family,
    fontStyle: "normal",
    fontWeight: font.h2.weight,
    fontSize: 14,
    marginLeft: "18%",
  },
  buttonToRegister: {
    position: "absolute",
    width: "85%",
    height: 52,
    left: "7.5%",
    top: 545,
    backgroundColor: colors.gradientOrange.primary,
    borderRadius: 20,
  },
});

export default HomeScrenStyle;
